# -*- coding: utf-8 -*-
"""Stable Diffusion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uePFjRTwZh__LcHZ7GC3_wFMrzKETxHK
"""

!pip install --upgrade keras-cv
!pip install translate
!pip install -q gradio

import time
import keras_cv
from tensorflow import keras
import matplotlib.pyplot as plt
import gradio as gr
from translate import Translator

model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)

def plot_images(images):
    plt.figure(figsize=(20, 20))
    for i in range(len(images)):
        ax = plt.subplot(1, len(images), i + 1)
        plt.imshow(images[i])
        plt.axis("off")
        plt.tight_layout()

def generate_images(text, n=3):
    translator = Translator(from_lang="ko", to_lang="en")
    print(text)
    translation = translator.translate(text)
    print(translation)

    images = model.text_to_image(translation, batch_size=n)

    return images

def inference(text):
    image = generate_images(text, 1).squeeze()
    return image

demo = gr.Interface(fn=inference, inputs="text", outputs="image")

demo.launch(debug=True)